DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS films;

DROP TABLE IF EXISTS film_genres;

DROP TABLE IF EXISTS ratingMPA;

DROP TABLE IF EXISTS genres;

DROP TABLE IF EXISTS friends;

DROP TABLE IF EXISTS likes;

CREATE TABLE users(
id int generated by default as identity primary key,
login varchar(255) not null,
name varchar(255),
email varchar(255) not null,
birthday date
);

CREATE TABLE films(
id int generated by default as identity primary key,
name varchar(255) not null,
description varchar(200),
release_date date not null,
duration int,
mpa int
);

CREATE TABLE genres(
id int generated by default as identity primary key,
name varchar
);

CREATE TABLE film_genres(
id int generated by default as identity primary key,
film_id int,
genre_id int
);

CREATE TABLE ratingMPA(
id int generated by default as identity primary key,
name varchar
);

CREATE TABLE friends(
id int generated by default as identity primary key,
user_id int,
friend_id int
);

CREATE TABLE likes(
id int generated by default as identity primary key,
user_id int,
film_id int
);