DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS films;

DROP TABLE IF EXISTS film_genres;

DROP TABLE IF EXISTS ratingMPA;

CREATE TABLE users(
id int generated by default as identity primary key,
login varchar,
name varchar,
email varchar,
birthday date
);

CREATE TABLE films(
id int generated by default as identity primary key,
name varchar,
description varchar,
release_date date,
duration int
);

CREATE TABLE film_genres(
id int generated by default as identity primary key,
name varchar
);

CREATE TABLE ratingMPA(
id int generated by default as identity primary key,
name varchar
);